#-------------------------------------------------------------------------------
#   IO Implementation in x86_64 Assembly Language with C Interface
#   Copyright (C) 2026  J. McIntosh
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License along
#   with this program; if not, write to the Free Software Foundation, Inc.,
#   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#-------------------------------------------------------------------------------
ARCH := -march=x86-64 -m64
IO_OBJ = ../io/libio.so
demo: main.o $(IO_OBJ)
	gcc -O3 $(ARCH) -z noexecstack main.o $(IO_OBJ) -o demo
main.o: main.c
	gcc -O3 $(ARCH) -Wall -c main.c -o main.o
.PHONY: clean
clean:
	rm -f demo main.o
